import { getBasePrintStyles } from './base-styles';
import type { PaymentsOverviewData } from './types';

export function generatePaymentsOverviewHtml(data: PaymentsOverviewData): string {
  const {
    schoolName,
    schoolLogo,
    currentTerm,
    generatedAt,
    currencySymbol = '$',
    todayTotal,
    todayCount,
    weekTotal,
    weekCount,
    monthTotal,
    yearTotal,
    expectedTermTotal,
    paidTermTotal,
    outstandingTerm,
    expectedYearTotal,
    paidYearTotal,
    outstandingYear,
  } = data;

  const formatCurrency = (cents: number) =>
    `${currencySymbol}${(cents / 100).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  ${getBasePrintStyles()}
  <style>
    .receipt-container {
      padding: 20px;
      max-width: 320px;
      margin: 0 auto;
      font-family: 'Courier New', Courier, monospace;
    }
    .header {
      text-align: center;
      padding-top: 16px;
      margin-bottom: 16px;
    }
    .header .title {
      font-size: 16px;
      font-weight: 700;
      margin-bottom: 4px;
    }
    .header .school-name {
      font-size: 13px;
      font-weight: 600;
    }
    .header .meta {
      font-size: 10px;
      margin-top: 4px;
    }
    .header .powered {
      font-size: 9px;
      margin-top: 2px;
    }
    .section {
      padding: 12px 0;
      border-bottom: 1px dashed #333;
    }
    .section-title {
      font-size: 9px;
      font-weight: 600;
      margin-bottom: 8px;
      border-bottom: 1px solid #333;
      padding-bottom: 2px;
    }
    .row {
      display: flex;
      justify-content: space-between;
      margin-bottom: 4px;
      font-size: 10px;
    }
    .row .label {
      color: #374151;
    }
    .row .value {
      font-weight: 600;
    }
    .row .value.highlight {
      color: #f97316;
    }
    .row .value.success {
      color: #059669;
    }
    .row .value.danger {
      color: #dc2626;
    }
    .row .value.paid {
      color: #059669;
    }
    .footer {
      font-size: 9px;
      text-align: center;
      padding-top: 12px;
      margin-top: 8px;
    }
  </style>
</head>
<body>
  <div class="receipt-container">
    <div class="header">
      <div class="title">SCHOOL PAYMENTS OVERVIEW</div>
      <div class="school-name">${schoolName}</div>
      <div class="meta">${currentTerm} • ${generatedAt}</div>
      <div class="powered">Powered by SchoolFoundry</div>
    </div>

    <div class="section">
      <div class="section-title">DAILY TOTALS</div>
      <div class="row">
        <span class="label">Today:</span>
        <span class="value">${formatCurrency(todayTotal)} <span style="color: #6b7280; font-weight: 400;">(${todayCount} payments)</span></span>
      </div>
      <div class="row">
        <span class="label">This Week:</span>
        <span class="value">${formatCurrency(weekTotal)} <span style="color: #6b7280; font-weight: 400;">(${weekCount} payments)</span></span>
      </div>
      <div class="row">
        <span class="label">This Month:</span>
        <span class="value">${formatCurrency(monthTotal)}</span>
      </div>
      <div class="row">
        <span class="label">Year to Date:</span>
        <span class="value highlight">${formatCurrency(yearTotal)}</span>
      </div>
    </div>

    <div class="section">
      <div class="section-title">CURRENT PERIOD: ${currentTerm}</div>
      <div class="row">
        <span class="label">Received:</span>
        <span class="value paid">${formatCurrency(paidTermTotal)}</span>
      </div>
      <div class="row">
        <span class="label">Expected:</span>
        <span class="value">${formatCurrency(expectedTermTotal)}</span>
      </div>
      <div class="row">
        <span class="label">Outstanding:</span>
        <span class="value ${outstandingTerm > 0 ? 'danger' : 'success'}">${formatCurrency(outstandingTerm)}</span>
      </div>
    </div>

    <div class="section">
      <div class="section-title">FULL YEAR</div>
      <div class="row">
        <span class="label">Received:</span>
        <span class="value paid">${formatCurrency(paidYearTotal)}</span>
      </div>
      <div class="row">
        <span class="label">Expected:</span>
        <span class="value">${formatCurrency(expectedYearTotal)}</span>
      </div>
      <div class="row">
        <span class="label">Outstanding:</span>
        <span class="value ${outstandingYear > 0 ? 'danger' : 'success'}">${formatCurrency(outstandingYear)}</span>
      </div>
    </div>

    <div class="footer">
      Generated by SchoolFoundry
    </div>
  </div>
</body>
</html>
`;
}
