import { getBasePrintStyles } from './base-styles';
import type { PaymentStatementData } from './types';

export function generatePaymentStatementHtml(data: PaymentStatementData): string {
  const { schoolName, period, currencySymbol = '$', payments, total } = data;

  const paymentRows = payments
    .map(
      p => `
    <tr>
      <td style="padding: 6px 8px; border-bottom: 1px dashed #ccc;">${p.date}</td>
      <td style="padding: 6px 8px; border-bottom: 1px dashed #ccc;">${p.receiptNumber}</td>
      <td style="padding: 6px 8px; border-bottom: 1px dashed #ccc;">${p.studentName}</td>
      <td style="padding: 6px 8px; border-bottom: 1px dashed #ccc;">${p.period}</td>
      <td style="padding: 6px 8px; border-bottom: 1px dashed #ccc;">${p.recordedBy}</td>
      <td style="padding: 6px 8px; border-bottom: 1px dashed #ccc; text-align: right;">$${p.amount}</td>
    </tr>
  `
    )
    .join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  ${getBasePrintStyles()}
  <style>
    .statement-container { padding: 40px; }
    .header { text-align: center; margin-bottom: 24px; }
    .header h1 { font-size: 18px; font-weight: 700; margin-bottom: 4px; }
    .header .school { font-size: 14px; margin-top: 4px; }
    .header .period { font-size: 11px; color: #666; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 10px; }
    th { padding: 8px; text-align: left; border-bottom: 1px solid #333; font-weight: 600; }
    .total-row { background-color: #f9f9f9; font-weight: 600; border-top: 2px solid #333; }
    .total-row td { padding: 12px; }
    .footer { margin-top: 24px; text-align: center; font-size: 9px; color: #666; border-top: 1px dashed #333; padding-top: 12px; }
  </style>
</head>
<body>
  <div class="statement-container">
    <div class="header">
      <h1>PAYMENT STATEMENT</h1>
      <div class="school">${schoolName}</div>
      <div class="period">${period}</div>
    </div>
    
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Receipt No.</th>
          <th>Learner</th>
          <th>Period</th>
          <th>Recorded By</th>
          <th style="text-align: right;">Amount</th>
        </tr>
      </thead>
      <tbody>
        ${paymentRows}
        <tr class="total-row">
          <td colspan="5" style="text-align: right;">TOTAL:</td>
          <td style="text-align: right;">${currencySymbol}${total}</td>
        </tr>
      </tbody>
    </table>
    
    <div class="footer">
      Generated by SchoolFoundry - Jiggabyte Technology Limited
    </div>
  </div>
</body>
</html>
`;
}
